// Build step for tokens.json (PRD §15.1). Resolves {group.token} aliases,
// then emits:
//   dist/tokens.css — CSS custom properties (theme-independent tier-1
//     scales, plus tier-2 semantic vars restated per [data-theme] and
//     prefers-color-scheme) and a Tailwind v4 `@theme` block that aliases
//     them to utility-class-friendly names.
//   dist/tokens.ts  — typed constants for JS-side use (e.g. a
//     StatusIndicator picking a colour programmatically).
//
// Tailwind v4 configures via CSS `@theme` blocks, not tailwind.config.js —
// see the note in phase00-instructions.txt; this build step is written for
// that mechanism specifically, not the older JS-config approach the PRD's
// wording assumes.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(__dirname, "tokens.json"), "utf-8"));

const ALIAS_RE = /^\{([\w.-]+)\}$/;

function resolve(value, root) {
  if (typeof value !== "string") return value;
  const match = value.match(ALIAS_RE);
  if (!match) return value;
  const path = match[1].split(".");
  let node = root;
  for (const key of path) node = node?.[key];
  if (node === undefined) throw new Error(`Unresolved token alias: ${value}`);
  return resolve(node.$value, root);
}

function flatten(node, root, prefix = []) {
  const out = [];
  if (node && typeof node === "object" && "$value" in node) {
    out.push([prefix.join("-"), resolve(node.$value, root)]);
    return out;
  }
  if (node && typeof node === "object") {
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith("$")) continue;
      out.push(...flatten(child, root, [...prefix, key]));
    }
  }
  return out;
}

const primitiveVars = flatten(tokens.primitive, tokens);
const lightVars = flatten(tokens.semantic.light, tokens);
const darkVars = flatten(tokens.semantic.dark, tokens);
const yardVars = flatten(tokens.semantic.yard, tokens);
const componentVars = flatten(tokens.component, tokens);

function toCssBlock(vars, indent = "  ") {
  return vars.map(([name, value]) => `${indent}--${name}: ${cssValue(value)};`).join("\n");
}

function cssValue(value) {
  if (Array.isArray(value)) return `cubic-bezier(${value.join(", ")})`;
  return String(value);
}

// Only the tier-1 scales that aren't colour (space/radius/font/duration/
// easing) are theme-independent enough to live once on :root. Colour
// primitives exist only to be resolved into semantic tokens above — they
// are deliberately NOT re-exposed as top-level CSS vars, so nothing in the
// app can reach past the semantic layer and hard-code a primitive hue.
const themeIndependentPrimitives = primitiveVars.filter(([name]) => !name.startsWith("color-"));

// Semantic bg.* / fg.* / border.* / accent.* / status.* names shorten to
// Tailwind-friendly utility aliases (bg-canvas, text-fg-primary,
// border-subtle, ...) rather than relying on Tailwind's own multi-segment
// name derivation, which would double up on "bg-bg-canvas" for
// `--color-bg-canvas`. "bg" and "border" stutter against Tailwind's own
// bg-*/border-* utility prefixes and are stripped; "fg"/"accent"/"status"
// read fine left in (text-fg-primary, bg-accent-default) and stripping
// "fg" specifically would make bg-primary/text-primary ambiguous about
// which semantic scale they came from.
const STUTTERING_PREFIXES = ["bg-", "border-"];

function themeAliasBlock(vars) {
  return vars
    .filter(([name]) => name.startsWith("color-") || name === "focus-ring")
    .map(([name]) => {
      let aliasName = name.startsWith("color-") ? name.slice("color-".length) : name;
      for (const prefix of STUTTERING_PREFIXES) {
        if (aliasName.startsWith(prefix)) {
          aliasName = aliasName.slice(prefix.length);
          break;
        }
      }
      return `  --color-${aliasName}: var(--${name});`;
    })
    .join("\n");
}

function elevationAliasBlock(vars) {
  return vars
    .filter(([name]) => name.startsWith("elevation-"))
    .map(([name]) => `  --shadow-${name.slice("elevation-".length)}: var(--${name});`)
    .join("\n");
}

const css = `/* GENERATED by packages/design-tokens/build.mjs — do not hand-edit. */

:root {
${toCssBlock(themeIndependentPrimitives)}
${toCssBlock(lightVars)}
${toCssBlock(componentVars)}
}

/* Dark: only when no explicit theme is chosen (system default) AND the
   user hasn't explicitly picked light. Guarded per the artifact/theme
   convention of never redefining a colour solely inside a media query —
   the full light palette above is the baseline these override. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]):not([data-theme="yard"]) {
${toCssBlock(darkVars)}
  }
}

/* Explicit choice always wins, in both directions. */
:root[data-theme="dark"] {
${toCssBlock(darkVars)}
}

:root[data-theme="yard"] {
${toCssBlock(yardVars)}
}

/* Tailwind v4 theme layer — aliases semantic tokens to utility-class-
   friendly names (bg-canvas, text-fg-primary, border-default, ...). */
@theme inline {
${themeAliasBlock(lightVars)}
${elevationAliasBlock(lightVars)}
  --radius-none: var(--radius-none);
  --radius-sm: var(--radius-sm);
  --radius-md: var(--radius-md);
  --radius-lg: var(--radius-lg);
  --radius-xl: var(--radius-xl);
  --radius-full: var(--radius-full);
  --font-size-xs: var(--font-size-xs);
  --font-size-sm: var(--font-size-sm);
  --font-size-base: var(--font-size-base);
  --font-size-lg: var(--font-size-lg);
  --font-size-xl: var(--font-size-xl);
  --font-size-2xl: var(--font-size-2xl);
  --font-size-3xl: var(--font-size-3xl);
  --font-size-4xl: var(--font-size-4xl);
  --font-size-5xl: var(--font-size-5xl);
  --font-size-6xl: var(--font-size-6xl);
}
`;

const allResolved = Object.fromEntries([
  ...primitiveVars,
  ...lightVars.map(([n, v]) => [`light-${n}`, v]),
  ...darkVars.map(([n, v]) => [`dark-${n}`, v]),
  ...yardVars.map(([n, v]) => [`yard-${n}`, v]),
  ...componentVars,
]);

const ts = `// GENERATED by packages/design-tokens/build.mjs — do not hand-edit.
export const tokens = ${JSON.stringify(allResolved, null, 2)} as const;
export type TokenName = keyof typeof tokens;
`;

mkdirSync(join(__dirname, "dist"), { recursive: true });
writeFileSync(join(__dirname, "dist", "tokens.css"), css);
writeFileSync(join(__dirname, "dist", "tokens.ts"), ts);
console.log(`Wrote ${primitiveVars.length + lightVars.length} vars to dist/tokens.css and dist/tokens.ts`);
