/**
 * Single source of truth for user-facing copy (PRD §16 — "no user-facing
 * string hard-coded in a component... route all copy through a single
 * strings module"). Not required for v1 i18n, but the pattern starts now,
 * with this phase's own screens, rather than as a later find-and-replace
 * across every phase that follows.
 */
export const strings = {
  auth: {
    login: {
      title: "Sign in",
      emailLabel: "Email",
      passwordLabel: "Password",
      totpLabel: "Authenticator code",
      totpHint: "Required for Owner and Accountant accounts.",
      submit: "Sign in",
      submitting: "Signing in…",
      genericError: "Something went wrong. Please try again.",
    },
    acceptInvite: {
      title: "Set up your account",
      passwordLabel: "Choose a password",
      passwordHint: "At least 12 characters.",
      submit: "Activate account",
      submitting: "Activating…",
      mfaTitle: "Set up two-factor authentication",
      mfaHint: "Scan this with your authenticator app, then enter the 6-digit code to confirm.",
      mfaCodeLabel: "6-digit code",
      mfaSubmit: "Confirm and continue",
      missingToken: "This invite link is missing its token.",
    },
    errors: {
      INVALID_CREDENTIALS: "Incorrect email or password.",
      MFA_REQUIRED: "Enter your authenticator code to continue.",
      MFA_INVALID: "That code is incorrect or has expired.",
      ACCOUNT_NOT_ACTIVE: "This account is not active.",
      RATE_LIMITED: "Too many attempts. Please wait a moment and try again.",
      INVALID_TOKEN: "This link is invalid or has expired.",
    },
  },
  shell: {
    signOut: "Sign out",
    roleLabels: {
      OWNER: "Owner",
      ACCOUNTANT: "Accountant",
      BUYER: "Buyer",
    },
    emptyState: {
      title: "Nothing here yet",
      body: "This screen fills in as later phases ship — the DNBP engine, ingestion, and publication flow all land in front of it.",
    },
    nav: {
      home: "Home",
      workbench: "Workbench",
      benchmarkCompare: "Benchmark Compare",
      correctionRequests: "Correction Requests",
      referenceData: "Reference Data",
      buyInstructions: "Buy Instructions",
      dashboard: "Dashboard",
      users: "Users",
    },
  },
  home: {
    title: "Today",
    deadlineLabel: "Submission deadline (Melbourne)",
    deadlinePassed: "Deadline passed — no submission received today",
    pipeline: {
      title: "Pipeline",
      steps: {
        receive: "Receive",
        validate: "Validate",
        calculate: "Calculate",
        review: "Review",
        publish: "Publish",
      },
    },
    tiles: {
      activeOrders: "Active orders",
      totalExposure: "Total exposure (AUD)",
      headsRequired: "Heads required",
      openCorrections: "Open correction requests",
    },
    publicationState: {
      title: "Publication",
      none: "Nothing published yet",
      live: "Live since",
    },
  },
  referenceData: {
    title: "Reference Data",
    model: {
      title: "The DNBP model",
      subtitle: "Bobby and Bing's shared workbench — every change is versioned, previewed, and audited.",
      cifBuffer: "CIF buffer (AUD/kg)",
      dnbpFactor: "DNBP factor by species",
      standardWeight: "Standard weight by species (kg)",
      editButton: "Propose a change",
      versionHistory: "Version history",
      active: "Active",
    },
    editor: {
      title: "Propose a reference-data change",
      effectiveFrom: "Effective from",
      note: "Note",
      addSpeciesRow: "Add species",
      previewButton: "Preview impact",
      previewing: "Computing impact…",
    },
    impact: {
      title: "Impact preview",
      warning: "This changes what the buyer may pay. Review every affected line before activating.",
      linesAffected: "lines affected",
      aggregateExposure: "Aggregate AUD exposure change",
      activateButton: "Activate this version",
      activating: "Activating…",
      confirmTitle: "Confirm activation",
      confirmBody: "This takes effect immediately for every active order line. This cannot be undone (only superseded by a later version).",
    },
    abattoir: {
      title: "Abattoir tables",
      subtitle: "Maintained by the abattoir and received with each submission — not editable here.",
      drift: "Drift awaiting review",
      noDrift: "No drift detected.",
      acknowledge: "Acknowledge",
    },
    registries: {
      speciesTitle: "Species registry",
      productTypeTitle: "Product type registry",
      addSpecies: "Add species",
      addProductType: "Add product type",
      code: "Code",
      displayName: "Display name",
      pricingStatus: "Pricing status",
      readyToPrice: "Ready to price",
      missingFactor: "No factor configured — add one to publish a price for it",
    },
  },
  benchmarkCompare: {
    title: "Benchmark Compare",
    subtitle: "Bing DNBP is the source of truth. The abattoir benchmark is reference only.",
    sourceOfTruth: "Bing DNBP — source of truth",
    benchmarkOnly: "Abattoir benchmark — reference only",
    impliedFactor: "Financier implied factor",
    noBenchmark: "No benchmark in this submission",
    aggregateBySpecies: "Aggregate impact by species",
  },
  correctionRequests: {
    title: "Correction Requests",
    subtitle: "Internal flags on received data — resolved with the abattoir by phone or email, never sent from here.",
    empty: "No correction requests.",
    withdraw: "Withdraw",
    autoResolved: "Auto-resolved by a later snapshot",
  },
  users: {
    title: "Users",
    invite: "Invite",
    inviteDialogTitle: "Invite a user",
    email: "Email",
    role: "Role",
    status: "Status",
    lastActive: "Last active",
    never: "Never",
    changeRole: "Change role",
    deactivate: "Deactivate",
    reactivate: "Reactivate",
    deactivateConfirm: "Revokes all active sessions immediately. Their upload and publication history is kept.",
    lastOwnerGuard: "Cannot deactivate the platform's last remaining active Owner.",
  },
  theme: {
    toggleLabel: "Theme",
    light: "Light",
    dark: "Dark",
    yard: "Yard",
  },
  buyer: {
    nav: { dnbp: "DNBP", bidCheck: "Bid Check", buyLog: "Buy Log", instruction: "Instruction", scorecard: "Scorecard" },
    instruction: {
      title: "Instruction",
      none: "No Buy Instruction has been issued yet.",
      statusLabel: "Status",
      contractLabel: "Contract",
      targetHeads: "Target heads",
      weightRequirement: "Weight requirement",
      dnbp: "Do not buy price",
      saleyard: "Saleyard",
      prepaymentNote: "Prepayment note",
      acknowledge: "Acknowledge",
      acknowledging: "Acknowledging…",
      acknowledged: "Acknowledged",
    },
    dnbpHome: {
      title: "Do Not Buy Price",
      live: "LIVE",
      offline: "Offline",
      updatedPrefix: "Updated",
      stale: "This price is from yesterday — pull to refresh",
      noPublication: "No Do Not Buy Price has been published yet.",
      perKg: "per kg",
      headsSuffix: "hd",
    },
    bidCheck: {
      title: "Bid Check",
      speciesLabel: "Species",
      pricePerHeadLabel: "Price per head",
      weightLabel: "Weight (kg)",
      resultSuffix: "/ kg",
      maxPricePrefix: "Max price for",
      dnbpIs: "DNBP is",
      overDnbp: "over DNBP",
      headroom: "headroom",
      pass: "PASS",
      close: "CLOSE",
      breach: "BREACH",
      logThisBuy: "Log this buy",
      logAnyway: "Log this buy anyway",
    },
    buyLog: {
      title: "Buy Log",
      agentLabel: "Agent",
      penLabel: "Pen",
      headsLabel: "No.",
      priceLabel: "Price",
      weightLabel: "Weight",
      descLabel: "Desc.",
      speciesLabel: "Species",
      freightLabel: "Freight",
      costLabel: "Cost",
      save: "Save entry",
      saving: "Saving…",
      breachReasonLabel: "Reason for breach",
      breachReasons: ["Quality premium", "Volume fill", "Market short", "Other"],
      duplicateWarning: "Same agent, pen and price logged in the last 2 minutes — check this isn't a duplicate.",
      totals: { heads: "Heads", kg: "Total kg", spend: "Spend", avg: "Avg $/kg", breaches: "Breaches" },
      empty: "No buys logged yet today.",
    },
    sync: {
      queued: "Queued",
      syncing: "Syncing…",
      synced: "Synced",
      conflict: "Failed — will retry",
      syncNow: "Sync now",
    },
    install: {
      prompt: "Install this app for offline use at the yard.",
      install: "Install",
      dismiss: "Not now",
    },
  },
  buyInstructions: {
    title: "Buy Instructions",
    generate: "Generate from current publication",
    generating: "Generating…",
    noPublication: "Publish a Do Not Buy Price first — a Buy Instruction is generated from a live publication.",
    empty: "No Buy Instructions yet.",
    statusLabel: "Status",
    approve: "Approve",
    approving: "Approving…",
    approvedBy: "Approved by",
    issue: "Issue to buyer",
    issuing: "Issuing…",
    reconcileClose: "Close as reconciled",
    closing: "Closing…",
    lineItems: "Line items",
    columns: {
      contract: "Order number",
      schw: "SCHW",
      expectedHeads: "Expected heads",
      weightRequirement: "Weight requirement",
      dnbp: "Do not buy price",
      petersExpectation: "Peter's expectation",
      expectedCost: "Expected Livestock Cost",
      fills: "Fills (kg)",
      balance: "Balance",
    },
    addFill: "Add fill",
    fillLabel: "Label",
    fillAmount: "Amount (kg)",
    removeFill: "Remove",
    reconciliation: {
      title: "Reconciliation",
      subtitle: "Trading week",
      saleyard: "Saleyard",
      schw: "SCHW",
      heads: "Heads",
      actualCostColumn: "Actual Cost",
      summary: "Summary",
      actualHeads: "Actual Heads",
      expectedHeads: "Expected Heads",
      orderedSchw: "Ordered SCHW (A)",
      boughtSchw: "Bought SCHW (B)",
      surplusShortfall: "Surplus/shortfall SCHW (A − B)",
      expectedCost: "Expected Cost (C)",
      actualCost: "Actual Cost (D)",
      costVariance: "Cost Variance (C − D)",
    },
    export: { title: "Export", pdf: "PDF", xlsx: "XLSX", exporting: "Exporting…" },
  },
  publication: {
    publish: {
      title: "Publish Do Not Buy Price",
      summaryTitle: "Species going out to the buyer",
      warningsTitle: "Warnings requiring acknowledgement",
      acknowledge: "Acknowledge",
      acknowledged: "Acknowledged",
      confirm: "Publish",
      confirming: "Publishing…",
      blocked: "Cannot publish — one or more active lines are blocked (see the Workbench).",
      nothingToAcknowledge: "No outstanding warnings on active lines.",
      deliveryTitle: "Delivery",
      notYetSeen: "Not yet seen",
      delivered: "Delivered",
      success: "Published",
    },
  },
  dashboard: {
    title: "Dashboard",
    subtitle: "Are we covered, are we buying well, where is my margin leaking?",
    panels: {
      orderBook: {
        title: "Order book",
        subtitle: "Active exposure, heads required vs bought, days of cover",
        exposureBySpecies: "Exposure by species",
        exposureByCustomer: "Exposure by customer",
        headsRequiredVsBought: "Heads required vs bought",
        daysOfCover: "Days of cover",
        daysOfCoverHint:
          "Remaining heads needed ÷ the trailing 7-day bought rate. Shown as — when nothing has been bought in the last 7 days.",
        totalExposure: "Total active exposure",
      },
      dnbpTrend: {
        title: "DNBP trend",
        subtitle: "The gap between the ceiling and what was actually paid is the margin story",
        speciesLabel: "Species",
        daysLabel: "Trailing days",
        heroLabel: "Published DNBP",
        referenceLabel: "Actual paid $/kg",
      },
      buyerPerformance: {
        title: "Buyer performance",
        subtitle: "Headroom captured, breach rate, avg variance — by buyer and saleyard",
        byBuyer: "By buyer",
        bySaleyard: "By saleyard",
        headroomCaptured: "Headroom captured (AUD)",
      },
      marginBridge: {
        title: "Margin bridge",
        subtitle: "From sell price through the CIF buffer to the Do Not Buy Price",
      },
      fulfilment: {
        title: "Fulfilment",
        subtitle: "Instructed vs bought SCHW, by trade date",
        instructed: "Instructed SCHW (kg)",
        bought: "Bought SCHW (kg)",
      },
      exceptions: {
        title: "Exceptions",
        subtitle: "Breaches, blocked lines, stale publications, undelivered instructions",
        breaches: "Breaches",
        blockedLines: "Blocked lines",
        stalePublications: "Stale publications",
        undeliveredInstructions: "Undelivered instructions",
        undeliveredPublications: "Undelivered to buyer",
        none: "None in this window.",
      },
    },
    kpis: {
      activeExposure: "Active exposure",
      headsRequired: "Heads required",
      headsBought: "Heads bought",
      openCorrections: "Open correction requests",
      breaches: "Breaches",
      blockedLines: "Blocked lines",
    },
  },
  scorecard: {
    title: "Scorecard",
    subtitle: "Your own performance — savings delivered, not surveillance.",
    rangeLabel: "Range",
    ranges: { today: "Today", days7: "7 days", days30: "30 days" },
    headsBought: "Heads bought",
    headsTarget: "vs target",
    avgPaid: "Avg $/kg paid",
    avgDnbp: "Avg DNBP",
    headroomCaptured: "Headroom captured",
    breaches: "Breaches",
    spendBySaleyard: "Spend by saleyard",
    noEntries: "No buys logged in this range yet.",
  },
} as const;
